version: "3.8"
services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - moviesdb_data_container:/data/db
  mongo-seed:
    container_name: mongo-seed
    build: .
    depends_on:
      - mongodb
volumes:
  moviesdb_data_container:
